import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div class="container-fluid mx-0 px-0">
      <Head>
        <title>The Leaky Bucket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.main}>
        <h1>The Leaky Bucket</h1>
      </main>

      <footer className={styles.footer}>
        <div class="col-4">
          <h1>The Leaky Bucket</h1>
          <p>Social Media Section</p>
        </div>
        <div class="col-2">
          <p>Link Section 1</p>
          <p className={styles.footerLink}>Link 1</p>
          <p className={styles.footerLink}>Link 2</p>
        </div>
        <div class="col-2">
          <p>Link Section 2</p>
          <p className={styles.footerLink}>Link 1</p>
          <p className={styles.footerLink}>Link 2</p>
        </div>
        <div class="col-2">
          <p>Link Section 3</p>
          <p className={styles.footerLink}>Link 1</p>
          <p className={styles.footerLink}>Link 2</p>
        </div>
        <div class="col-2">
          <p>Link Section 4</p>
          <p className={styles.footerLink}>Link 1</p>
          <p className={styles.footerLink}>Link 2</p>
        </div>
      </footer>
    </div>
  )
}
